### ISSUE TITLE
Migrate DB

### ISSUE THREAD

**Issue by kiljw316** [gimgit/Pomomo-study-BE#49]
1. UserInfo 반환 시 가장 최근 peerId 같이 보내주기
2. 나가기 버튼 누를 때  방 Id랑 peerId 같이 보내준다.
3. DB 필드 변경 필요

**Comment by kiljw316** [comment]
나갈 떄 말고 들어올 떄 peerId 보내주기

**Comment by gimgit** [comment]
socket.js 34~ "join-room"이벤트에 저장
